services:
  admin_db:
    image: postgres:17.4
    hostname: admin_db
    volumes:
      - admin_db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${MYDB_ADMIN_USER}
      POSTGRES_PASSWORD: '${MYDB_ADMIN_PASSWORD}'
      POSTGRES_DB: 'mydb_admin'
    labels:
      'BACKUP_FREQ': 'Daily'
      'CONTACT': ${CONTACT_MAIL}
      'DB_NAME': 'mydb_admin'
      'DB_USER': 'mydbadmin'
      'DBaaS': 'true'
      'DESCRIPTION': 'MyDB DBaaS administrative DB'
      'OWNER': '${supportPerson}'
    tmpfs:
      - /dev/shm:size=1g
    ports:
      - '32009:5432'
    deploy:
      restart_policy:
        condition: any

volumes:
   admin_db:
     driver: local
