services:
  migrate_db:
    image: postgres:17.4
    hostname: migrate_db
    volumes:
      - migrate_db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${MYDB_ADMIN_USER} 
      POSTGRES_PASSWORD: ${MYDB_MIGRATE_PASSWORD} 
      POSTGRES_DB: 'mydb_admin'
      PGOPTIONS: "-c password_encryption=md5"
    labels:
      'BACKUP_FREQ': 'Daily'
      'CONTACT': ${CONTACT_MAIL} 
      'DB_NAME': 'mydb_admin'
      'DB_USER': 'mydbadmin'
      'DBaaS': 'true'
      'DESCRIPTION': 'MyDB DBaaS Migration Data'
      'OWNER': '${supportPerson}'
    tmpfs:
      - /dev/shm:size=1g
    ports:
      - '32008:5432'
    deploy:
      restart_policy:
        condition: any

volumes:
   migrate_db:
     driver: local
